<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>4.1</title>
    <style>
        /* Add any desired styling for the footer */
        footer {
        background-color: #9148e4;
        padding: 20px;
        text-align: center;
        }
        </style>
</head>
<body>
    <h1>4.1 แสดงชื่อ-นามสกุล ชื่อเล่น ด้วยตัวแปร</h1>
    <h2?><?PHP echo "Hello PHP";?></h2>
    <?PHP
    echo"<br>";
     echo "Nittaya Sansrichai";
     echo"<br>";
     $nickname="Awe";
     $Age=36;
     echo "Nickname :".$nickname;
     echo"<br>";
     echo"Age:".$Age;
     
     ?>
<h3><a href="Index.html">Home</a></h3>

</body>
<footer>Copyright&copy by Thonburi University</footer>
</html>